=== ArnaudVERSINI/XSLT/dynamic/xml/Albums.dtd
<!-- DTD des albums -->

<!ELEMENT Albums (Album*)>
<!ELEMENT Album (Titre, Annee?, Couverture?, Artiste, Support?, Pistes)>
<!ATTLIST Album id ID #REQUIRED>
<!ELEMENT Titre (#PCDATA)>
<!ELEMENT Annee (#PCDATA)>
<!ELEMENT Couverture EMPTY>
<!ATTLIST Couverture fichier CDATA #REQUIRED>
<!ELEMENT Artiste EMPTY>
<!ATTLIST Artiste ref CDATA #REQUIRED>
<!ELEMENT Support (Type, Prix)>
<!ELEMENT Pistes (Piste*)>
<!ELEMENT Piste (No, Titre, Duree)>
<!ELEMENT No (#PCDATA)>
<!ELEMENT Duree (#PCDATA)>
<!ELEMENT Type (#PCDATA)>
<!ELEMENT Prix (#PCDATA)>

=== ArnaudVERSINI/XSLT/static/xml/Albums.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE Albums SYSTEM "Albums.dtd">

<Albums>
  <Album id="C1" >
    <Titre>Titre1</Titre>
    <Annee>2008</Annee>
    <Couverture fichier=""/>
    <Artiste ref="A1"/>
    <Support>
      <Type>CD</Type>
      <Prix>25</Prix>
    </Support>
    <Pistes>
      <Piste>
        <No>1</No>
        <Titre>Intro</Titre>
        <Duree>2:56</Duree>
      </Piste>
    </Pistes>
  </Album>
  
  <Album id="C2" >
    <Titre>Titre2</Titre>
    <Annee>2008</Annee>
    <Couverture fichier=""/>
    <Artiste ref="A1"/>
    <Support>
      <Type>CD</Type>
      <Prix>25</Prix>
    </Support>
    <Pistes>
      <Piste>
        <No>1</No>
        <Titre>Intro2</Titre>
        <Duree>2:56</Duree>
      </Piste>
    </Pistes>
  </Album>
  
  <Album id="C3" >
    <Titre>Titre1</Titre>
    <Annee>2000</Annee>
    <Couverture fichier=""/>
    <Artiste ref="A2"/>
    <Support>
      <Type>CD</Type>
      <Prix>25</Prix>
    </Support>
    <Pistes>
      <Piste>
        <No>1</No>
        <Titre>Prélude</Titre>
        <Duree>2:56</Duree>
      </Piste>
    </Pistes>
  </Album>
</Albums>
